### ISSUE TITLE
adding JSON response doesn't seem to work

### ISSUE THREAD

**Issue by rdvanbuuren** [dukeofharen/httplaceholder#108]
I'm trying to add the following to my stubs, which comes from your own examples (https://github.com/dukeofharen/httplaceholder/blob/master/docs/RESPONSE.md#json):

```yaml
- id: situation-json
  conditions:
    method: GET
    url:
      path: /text.json
  response:
    statusCode: 200
    json: {"msg": "All OK!"}
``` 
This gives the following errors from the UI:
* Stub with ID 'situation-json' could not be added.
* Something went wrong while contacting the server.

Running HttPlaceholder 2020.8.23.62. Also, the previous version gave me the exact same error response.

Here's the verbose logging from the application:
```console
2021-01-06 16:32:21.773 +01:00 [DBG] Connection id "0HM5IB11A2C00" accepted.
2021-01-06 16:32:21.776 +01:00 [DBG] Connection id "0HM5IB11A2C00" started.
2021-01-06 16:32:21.827 +01:00 [INF] Request starting HTTP/1.1 POST http://127.0.0.1:5000/ph-api/stubs application/json;charset=UTF-8 136
2021-01-06 16:32:21.832 +01:00 [DBG] Wildcard detected, all requests with hosts will be allowed.
2021-01-06 16:32:21.846 +01:00 [DBG] POST requests are not supported
2021-01-06 16:32:21.848 +01:00 [DBG] POST requests are not supported
2021-01-06 16:32:21.849 +01:00 [DBG] POST requests are not supported
2021-01-06 16:32:21.872 +01:00 [DBG] Initializing Razor view compiler with no compiled views.
2021-01-06 16:32:21.914 +01:00 [DBG] 1 candidate(s) found for the request path '/ph-api/stubs'
2021-01-06 16:32:21.923 +01:00 [DBG] Endpoint 'HttPlaceholder.Controllers.v1.StubController.Add (HttPlaceholder)' with route pattern 'ph-api/stubs' is valid for the request path '/ph-api/stubs'
2021-01-06 16:32:21.933 +01:00 [DBG] Request matched endpoint 'HttPlaceholder.Controllers.v1.StubController.Add (HttPlaceholder)'
2021-01-06 16:32:21.945 +01:00 [INF] Executing endpoint 'HttPlaceholder.Controllers.v1.StubController.Add (HttPlaceholder)'
2021-01-06 16:32:21.961 +01:00 [DBG] Registered model binder providers, in the following order: ["Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BinderTypeModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ServicesModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.HeaderModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.FloatingPointTypeModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.EnumTypeModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.DateTimeModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.SimpleTypeModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.CancellationTokenModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ByteArrayModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.FormFileModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.FormCollectionModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.KeyValuePairModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.DictionaryModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ArrayModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.CollectionModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ComplexObjectModelBinderProvider"]
2021-01-06 16:32:22.076 +01:00 [INF] Route matched with {action = "Add", controller = "Stub"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.ActionResult`1[HttPlaceholder.Dto.v1.Stubs.FullStubDto]] Add(HttPlaceholder.Dto.v1.Stubs.StubDto) on controller HttPlaceholder.Controllers.v1.StubController (HttPlaceholder).
2021-01-06 16:32:22.087 +01:00 [DBG] Execution plan of authorization filters (in the following order): ["None"]
2021-01-06 16:32:22.097 +01:00 [DBG] Execution plan of resource filters (in the following order): ["Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.SaveTempDataFilter"]
2021-01-06 16:32:22.104 +01:00 [DBG] Execution plan of action filters (in the following order): ["Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648)", "Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000)", "Microsoft.AspNetCore.Mvc.Infrastructure.ModelStateInvalidFilter (Order: -2000)", "HttPlaceholder.Authorization.ApiAuthorizationAttribute (Order: 0)"]
2021-01-06 16:32:22.135 +01:00 [DBG] Execution plan of exception filters (in the following order): ["None"]
2021-01-06 16:32:22.137 +01:00 [DBG] Execution plan of result filters (in the following order): ["Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.SaveTempDataFilter", "Microsoft.AspNetCore.Mvc.Infrastructure.ClientErrorResultFilter (Order: -2000)", "HttPlaceholder.Authorization.ApiAuthorizationAttribute (Order: 0)"]
2021-01-06 16:32:22.142 +01:00 [DBG] Executing controller factory for controller HttPlaceholder.Controllers.v1.StubController (HttPlaceholder)
2021-01-06 16:32:22.148 +01:00 [DBG] Executed controller factory for controller HttPlaceholder.Controllers.v1.StubController (HttPlaceholder)
2021-01-06 16:32:22.160 +01:00 [DBG] Attempting to bind parameter 'stub' of type 'HttPlaceholder.Dto.v1.Stubs.StubDto' ...
2021-01-06 16:32:22.186 +01:00 [DBG] Attempting to bind parameter 'stub' of type 'HttPlaceholder.Dto.v1.Stubs.StubDto' using the name '' in request data ...
2021-01-06 16:32:22.189 +01:00 [DBG] Rejected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonPatchInputFormatter' for content type 'application/json;charset=UTF-8'.
2021-01-06 16:32:22.194 +01:00 [DBG] Selected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonInputFormatter' for content type 'application/json;charset=UTF-8'.
2021-01-06 16:32:22.203 +01:00 [DBG] Connection id "0HM5IB11A2C00", Request id "0HM5IB11A2C00:00000002": started reading request body.
2021-01-06 16:32:22.208 +01:00 [DBG] Connection id "0HM5IB11A2C00", Request id "0HM5IB11A2C00:00000002": done reading request body.
2021-01-06 16:32:22.353 +01:00 [DBG] JSON input formatter threw an exception.
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path 'response.json', line 1, position 118.
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
2021-01-06 16:32:22.378 +01:00 [DBG] JSON input formatter threw an exception.
Newtonsoft.Json.JsonReaderException: After parsing a value an unexpected character was encountered: :. Path 'response.json', line 1, position 123.
   at Newtonsoft.Json.JsonTextReader.ParsePostValue(Boolean ignoreComments)
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
2021-01-06 16:32:22.393 +01:00 [DBG] JSON input formatter threw an exception.
Newtonsoft.Json.JsonReaderException: After parsing a value an unexpected character was encountered: :. Path 'response.json', line 1, position 123.
   at Newtonsoft.Json.JsonTextReader.ParsePostValue(Boolean ignoreComments)
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.HandleError(JsonReader reader, Boolean readPastError, Int32 initialDepth)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
2021-01-06 16:32:22.418 +01:00 [DBG] Done attempting to bind parameter 'stub' of type 'HttPlaceholder.Dto.v1.Stubs.StubDto'.
2021-01-06 16:32:22.425 +01:00 [DBG] Done attempting to bind parameter 'stub' of type 'HttPlaceholder.Dto.v1.Stubs.StubDto'.
2021-01-06 16:32:22.428 +01:00 [DBG] Attempting to validate the bound parameter 'stub' of type 'HttPlaceholder.Dto.v1.Stubs.StubDto' ...
2021-01-06 16:32:22.431 +01:00 [DBG] Done attempting to validate the bound parameter 'stub' of type 'HttPlaceholder.Dto.v1.Stubs.StubDto'.
2021-01-06 16:32:22.435 +01:00 [DBG] The request has model state errors, returning an error response.
2021-01-06 16:32:22.440 +01:00 [DBG] Request was short circuited at action filter 'Microsoft.AspNetCore.Mvc.Infrastructure.ModelStateInvalidFilter'.
2021-01-06 16:32:22.446 +01:00 [DBG] List of registered output formatters, in the following order: ["Microsoft.AspNetCore.Mvc.Formatters.HttpNoContentOutputFormatter", "Microsoft.AspNetCore.Mvc.Formatters.StringOutputFormatter", "Microsoft.AspNetCore.Mvc.Formatters.StreamOutputFormatter", "Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter", "HttPlaceholder.Formatters.YamlOutputFormatter"]
2021-01-06 16:32:22.459 +01:00 [DBG] Attempting to select an output formatter based on Accept header '["application/json", "text/plain", "*/*"]' and explicitly specified content types '["application/problem+json", "application/problem+xml"]'. The content types in the accept header must be a subset of the explicitly set content types.
2021-01-06 16:32:22.466 +01:00 [DBG] Selected output formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter' and content type 'application/problem+json' to write the response.
2021-01-06 16:32:22.477 +01:00 [INF] Executing BadRequestObjectResult, writing value of type 'Microsoft.AspNetCore.Mvc.ValidationProblemDetails'.
2021-01-06 16:32:22.560 +01:00 [INF] Executed action HttPlaceholder.Controllers.v1.StubController.Add (HttPlaceholder) in 414.7998ms
2021-01-06 16:32:22.564 +01:00 [INF] Executed endpoint 'HttPlaceholder.Controllers.v1.StubController.Add (HttPlaceholder)'
2021-01-06 16:32:22.567 +01:00 [DBG] Connection id "0HM5IB11A2C00" completed keep alive response.
2021-01-06 16:32:22.576 +01:00 [INF] Request finished HTTP/1.1 POST http://127.0.0.1:5000/ph-api/stubs application/json;charset=UTF-8 136 - 400 574 application/problem+json;+charset=utf-8 753.8996ms
```

**Comment by dukeofharen** [comment]
Hi Rick, good catch, I will fix the docs.

If you want to add JSON to the stub, you can add single quotes around the JSON or make it multi line. Something like this:

```
- id: situation-json
  conditions:
    method: GET
    url:
      path: /text.json
  response:
    statusCode: 200
    json: '{"msg": "All OK!"}'
```

or

```
- id: situation-json
  conditions:
    method: GET
    url:
      path: /text.json
  response:
    statusCode: 200
    json: |
        {
            "msg": "All OK!"
        }
```
